---
title: "Testing crosstalk with sf polygons"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(tidyverse)
library(flexdashboard)
library(crosstalk)
library(leaflet)
library(sf)
library(d3scatter)

path_to_shapefile <- "D:/GIS/census/Census 2013/ESRI_Shapefile_Digital_Boundaries_2014_High_Def_Clipped/MB2014_HD_Clipped.shp"
path_to_mb_data <- "D:/GIS/census/Census 2013/2013_mb_dataset_Total_New_Zealand_CSV/mb2013_indiv1.csv"

mb_df <- read_csv(path_to_mb_data) %>% select(1:6)

mb_geom <- st_read(path_to_shapefile,
                    quiet = TRUE) %>% 
  filter(UA2014_NAM == "Whangarei") %>% 
  left_join(mb_df, by = c("MB2014" = "Code")) %>% 
  mutate(pop_density = `2013_Census_census_usually_resident_population_count(1)` / SHAPE_Area) %>% 
  select(MB2014, pop_density,
         pop_2001 = `2001_Census_census_usually_resident_population_count(1)`,
         pop_2013 = `2013_Census_census_usually_resident_population_count(1)`
         ) %>% 
  st_transform(crs = 4326)

mb_centr <- mb_geom %>% 
  mutate(geom2 = st_centroid(geometry)) %>% 
  st_set_geometry("geom2") %>% 
  select(-geometry)

shared_mb_centr <- SharedData$new(mb_centr, key = ~MB2014)

# the following is from https://stackoverflow.com/questions/42974140/crosstalk-filter-polylines-in-leaflet
# but doesn't seem to work, maybe due to a new version of leaflet

# shapes_to_filter <- mb_geom %>%as("Spatial")
# sd_map <- SharedData$new(shapes_to_filter)
# sd_df <- SharedData$new(as.data.frame(shapes_to_filter@data), group = sd_map$groupName())

```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart

```{r}
d3scatter(shared_mb_centr, ~pop_2001, ~pop_2013, width = "100%")
```

Column {data-width=600}
-----------------------------------------------------------------------

### Map

```{r}
density_pal <- colorNumeric("magma", domain = mb_geom$pop_density)

leaflet(shared_mb_centr) %>%
  addTiles(group = "OSM") %>%
  addPolygons(data = mb_geom, weight = 0.3, fillOpacity = 0.8,
              color = ~density_pal(pop_density)) %>%
  addCircles(color = "red", radius = 1)

```


