---
title: "Flexdashboard + crosstalk + leaflet"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
library(crosstalk)
library(d3scatter)
library(leaflet)
library(dygraphs)
library(reactable)
library(sparkline)
shared_mtcars <- SharedData$new(mtcars)
shared_iris <- SharedData$new(iris)
shared_quakes <- SharedData$new(quakes[sample(nrow(quakes), 100),])
```

Column {data-width=600}
-------------------------

### Quakes map

Note: leaflet seems to cause crashes when interacting with other htmlwidgets within flexdashboard, but only within the RStudio viewer. Seems fine in Chrome.

```{r}
leaflet(shared_quakes, width = "100%", height = 300) %>%
    addTiles() %>%
    addCircleMarkers()
```

### Depth vs magnitude

```{r}
d3scatter(shared_quakes, ~depth, ~mag, width = "100%", height = 300)
```

### Filters

```{r}
filter_slider("depth", "Depth", shared_quakes, ~depth, width = "100%")
filter_slider("magnitude", "Magnitude", shared_quakes, ~mag, width = "100%")
```

Column {data-width=400}
-------------------------

### Table

```{r}
bar_style <- function(width = 1, fill = "#e6e6e6", height = "75%", align = c("left", "right"), color = NULL) {
  align <- match.arg(align)
  if (align == "left") {
    position <- paste0(width * 100, "%")
    image <- sprintf("linear-gradient(90deg, %1$s %2$s, transparent %2$s)", fill, position)
  } else {
    position <- paste0(100 - width * 100, "%")
    image <- sprintf("linear-gradient(90deg, transparent %1$s, %2$s %1$s)", position, fill)
  }
  list(
    backgroundImage = image,
    backgroundSize = paste("100%", height),
    backgroundRepeat = "no-repeat",
    backgroundPosition = "center",
    color = color
  )
}

reactable(shared_quakes, bordered = TRUE, striped = TRUE, highlight = TRUE, 
          selection = "multiple", onClick = "select",
          columns = list(mag = colDef(name = "Magnitude",
                                      style = function(value) {
                                        bar_style(width = 0.9 * value / max(shared_quakes$data()$mag),
                                                  fill = "#2c5e77", color = "#fff")
                                        },
                                      align = "left"),
                         depth = colDef(name = "Depth"),
                         stations = colDef((name = "Num stations"))),
          defaultPageSize = 18,
          defaultColDef = colDef(footer = function(values) {
    if (!is.numeric(values)) return()
    sparkline(values, type = "box", width = 100, height = 30)
  }))
```

