---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(sf)
library(glue)
library(fs)
library(janitor)
library(leaflet)

this_area <- "Whangarei District"

path_to_shapefile <- "D:/GIS/census/Census 2013/ESRI_Shapefile_Digital_Boundaries_2014_High_Def_Clipped/MB2014_HD_Clipped.shp"
path_to_mb_data <- "D:/GIS/census/Census 2013/2013_mb_dataset_Total_New_Zealand_CSV/mb2013_indiv1.csv"

mb_df <- read_csv(path_to_mb_data) %>% select(1:6)

mb_geom <- st_read(path_to_shapefile,
                    quiet = TRUE) %>% 
  filter(TA2014_NAM == this_area) %>% # when this_area is a TA name
  left_join(mb_df, by = c("MB2014" = "Code")) %>% 
  mutate(pop_density = `2013_Census_census_usually_resident_population_count(1)` / SHAPE_Area) %>% 
  st_transform(crs = 4326)

# mock up data for small multiples
mb_range <- mb_geom$MB2014 %>% as.numeric() %>% range()
density_range <- mb_geom$pop_density %>% as.numeric() %>% range()

mock_stats <- mb_geom %>% 
  filter(pop_density > 1e-04) %>% 
  as_tibble() %>% 
  select(MB2014, v_1 = pop_density) %>% 
  mutate(MB = as.numeric(MB2014)) %>% 
  mutate(v_2 = (density_range[2] - v_1) *.6,
         v_3 = v_1 * (MB - mb_range[1]) / diff(mb_range),
         v_4 = v_2 * (MB - mb_range[1]) / diff(mb_range)
  ) %>% 
  pivot_longer(starts_with("v_"), names_to = "threshold", names_prefix = "v_") %>% 
  select(-MB) %>% 
  mutate(threshold = as.numeric(threshold) * 15)

mock_stats_sf <- mb_geom %>% 
  inner_join(mock_stats, by = "MB2014") %>% 
  select(MB2014, threshold, value, geometry)

value_pal <- colorNumeric("viridis", domain = density_range)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
leaflet() %>%
  addProviderTiles(providers$Stamen.Terrain, group = "Terrain") %>%
  addProviderTiles(providers$Esri.WorldTopoMap, group = "TopoMap") %>%
  addProviderTiles(providers$Esri.WorldImagery, group = "Aerial") %>%
  addTiles(group = "OSM") %>%
  addProviderTiles(providers$Stamen.TonerLite, group = "Toner Lite") %>%
  addPolygons(data = mock_stats_sf %>% filter(threshold == 15),
              group = "15",
                   label = ~glue("{MB2014}"),
                   stroke = TRUE, color = "white", opacity = 1, weight = 1,
                   fill = TRUE, fillColor = ~value_pal(value), fillOpacity = 0.8,
                   popup = ~glue("{MB2014}")) %>%
  addPolygons(data = mock_stats_sf %>% filter(threshold == 30),
              group = "30",
                   label = ~glue("{MB2014}"),
                   stroke = TRUE, color = "white", opacity = 1, weight = 1,
                   fill = TRUE, fillColor = ~value_pal(value), fillOpacity = 0.8,
                   popup = ~glue("{MB2014}")) %>%
  addPolygons(data = mock_stats_sf %>% filter(threshold == 45),
              group = "45",
                   label = ~glue("{MB2014}"),
                   stroke = TRUE, color = "white", opacity = 1, weight = 1,
                   fill = TRUE, fillColor = ~value_pal(value), fillOpacity = 0.8,
                   popup = ~glue("{MB2014}")) %>%
  addPolygons(data = mock_stats_sf %>% filter(threshold == 60),
              group = "60",
                   label = ~glue("{MB2014}"),
                   stroke = TRUE, color = "white", opacity = 1, weight = 1,
                   fill = TRUE, fillColor = ~value_pal(value), fillOpacity = 0.8,
                   popup = ~glue("{MB2014}")) %>%
  addLayersControl(baseGroups = c("Terrain", "TopoMap", "Aerial", "OSM", "Toner Lite"),
                   overlayGroups = c("15", "30", "45", "60"),
                   options = layersControlOptions(collapsed = FALSE)) %>%
  addMeasure(primaryLengthUnit = "meters", primaryAreaUnit = "sqmeters")

  
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
mock_stats_sf %>% as.data.frame() %>% count(threshold)
```

4 layers, 500 meshblocks per layer

Text output only: 880kB

One leaflet layer: 4.1MB

Two leaflet layers: 6.7MB

Four leaflet layers: 11.9MB

### Chart C

```{r}
mock_stats_sf %>% head(10)

```

